
services:
  gazebo:
    image: osrf/ros:humble-desktop-full
    platform: linux/amd64
    container_name: armstrong_gazebo
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/workspace
      - ./data:/data
      - ./gazebo_models:/home/ros/.gazebo/models
    ports:
      - "11345:11345"
      - "11346:11346"
      - "8765:8765"  # Foxglove bridge websocket
    command: >
      bash -c "
        apt-get update && apt-get install -y ros-humble-gazebo-ros-pkgs ros-humble-gazebo-ros ros-humble-ur-description ros-humble-moveit ros-humble-moveit-msgs ros-humble-moveit-ros-planning-interface ros-humble-cv-bridge ros-humble-image-transport ros-humble-foxglove-bridge &&
        source /opt/ros/humble/setup.bash &&
        cd /workspace &&
        colcon build --packages-select ur5_gazebo ur5_moveit_config &&
        source install/setup.bash &&
        echo 'Gazebo container ready. Exec into container to launch.' &&
        tail -f /dev/null
      "
    depends_on:
      - moveit

  moveit:
    image: osrf/ros:humble-desktop-full
    platform: linux/amd64
    container_name: armstrong_moveit
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/workspace
    command: >
      bash -c "
        apt-get update && apt-get install -y ros-humble-moveit ros-humble-moveit-msgs ros-humble-moveit-ros-planning-interface ros-humble-ur-description ros-humble-joint-state-publisher &&
        source /opt/ros/humble/setup.bash &&
        cd /workspace &&
        colcon build --packages-select ur5_moveit_config &&
        source install/setup.bash &&
        echo 'MoveIt container ready. Exec into container to launch.' &&
        tail -f /dev/null
      "

  rviz:
    image: osrf/ros:humble-desktop-full
    platform: linux/amd64
    container_name: armstrong_rviz
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_INDIRECT=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/workspace
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        cd /workspace &&
        source install/setup.bash &&
        echo 'RViz container ready. Launch RViz manually if needed.' &&
        tail -f /dev/null
      "
    depends_on:
      - moveit

  bc_training:
    image: tensorflow/tensorflow:2.13.0-gpu
    container_name: armstrong_bc_training
    volumes:
      - ./workspace:/workspace
      - ./data:/data
    command: >
      bash -c "
        cd /workspace &&
        python3 -m pip install -r requirements.txt &&
        python3 src/bc_training/train_policy.py
      "
    profiles:
      - cloud