joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 1.0
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    max_effort: 150.0